[package]
name = "raven-opt"
description = "raven-opt: optimise a raven-asm project into an optimised raven-asm project"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
documentation.workspace = true
readme = "README.md"
keywords = ["scratch", "sb3", "compiler", "optimiser", "cli"]
categories = ["command-line-utilities", "compilers"]

[[bin]]
name = "raven-opt"
path = "src/main.rs"

[dependencies]
clap.workspace = true
raven-asm = { path = "../raven-asm", version = "0.4.2" }
raven-scratch = { path = "../raven-scratch", version = "0.4.2" }
