// Generate the machine's tables and its image, and build the `.sb3`.
//
//     node tools/build.mjs             the image
//     node tools/build.mjs --stage 1280x900
//
// Three generated files come out of it:
//
//   src/rv32/tables.rav   the ALU's three 64 KiB logic tables, the 256 byte to
//                         character table, and nothing that depends on the
//                         guest. Generated once and committed.
//   src/rv32/image.rav    the guest's image and the device tree that describes
//                         the machine to it. Not committed: `raven build`
//                         compiles whatever it holds.
//   dist/rv32mini.sb3     the project.
//
// The image is this repository's own rather than a borrowed one: the reference's
// kernel with a second initramfs on the end of it, which the device tree points
// the kernel at. `tools/mini-image.sh` builds all three -- the image and the tree
// it goes with, both in `images/` -- so this tool reads those and builds.
//
// The image runs with the tree in the last 1728 bytes of RAM, which is where
// `examples/cli.rs` puts it and where the kernel's own decompressor leaves room
// for it.

import { execFileSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const repo = path.resolve(root, '..', '..', '..');

const IMAGE = { name: 'mini', file: 'images/mini_image', dtb: 'images/mini.dtb', manifest: 'raven-mini.toml' };

// ---------------------------------------------------------------------------
// Writing raven
// ---------------------------------------------------------------------------

const escape = (value) => (typeof value === 'string'
    ? `"${[...value].map((c) => {
        const code = c.codePointAt(0);
        return code === 34 || code === 92 ? '\\' + c
            : code >= 32 && code < 127 ? c
                : `\\u{${code.toString(16).toUpperCase().padStart(4, '0')}}`;
    }).join('')}"`
    : String(value));

/// One `pub var` per table. A list initializer is a literal the compiler bakes
/// into the project's own list, so nothing is pushed at run time.
function table(name, type, items, perLine) {
    const lines = [];
    for (let i = 0; i < items.length; i += perLine) {
        lines.push(items.slice(i, i + perLine).map(escape).join(', '));
    }
    return `pub var ${name}: list<${type}> = [\n${lines.join(',\n')}\n];`;
}

function write(relative, text) {
    const file = path.join(root, relative);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, text);
    return { file, size: text.length };
}

// ---------------------------------------------------------------------------
// The two files
// ---------------------------------------------------------------------------

/// Everything about the machine that does not depend on the guest.
function tables() {
    // The guest hands the console single bytes, so the terminal needs byte to
    // text and text to byte in both directions: the forward table is the list,
    // the backward one is `index_of`. Item 1 is code 0.
    const byteChars = [];
    for (let i = 0; i < 256; i++) byteChars.push(String.fromCharCode(i));

    // Scratch has no bitwise operator and raven does not add one, so a 32 bit
    // AND is four lookups into a table indexed by the two bytes of a 16 bit
    // pair. mini-rv32ima builds these at startup; they are the same 65536
    // values, written as a literal so that nothing has to build them.
    const or = [], and = [], xor = [];
    for (let i = 0; i < 256; i++) {
        for (let j = 0; j < 256; j++) {
            or.push(i | j);
            and.push(i & j);
            xor.push(i ^ j);
        }
    }

    return `// The machine's read-only tables, generated by tools/build.mjs. Do not edit.
//
// The three logic tables are the ALU: Scratch has no bitwise operator, so a 32
// bit AND, OR or XOR is four lookups into a table indexed by the two bytes of a
// 16 bit pair, and the tables cost nothing to start because a list initializer
// is a literal.
//
// The terminal draws through penfont, which has no idea what a byte is, so
// \`byte_chars\` is the other half of the console: item i is the character the
// guest's byte i-1 means, and \`index_of\` is the way back.

${table('byte_chars', 'str', byteChars, 16)}

${table('or_lut', 'num', or, 64)}

${table('and_lut', 'num', and, 64)}

${table('xor_lut', 'num', xor, 64)}
`;
}

function image(name, bytes, dtb, source) {
    return `// The guest's image and its device tree, generated by tools/build.mjs.
// Do not edit: \`node tools/build.mjs\` writes this file, and the image it holds
// is the image the project boots.
//
// From ${source} (${bytes.length} bytes) and ${dtb.length} bytes of device tree.
// The tree is placed in the last 1728 bytes of RAM, which is where the reference
// puts it and where the image's own stub leaves room for it: the bytes at
// 0x8000_0000 unpack the kernel to 0x8100_0000, so anything between the image
// and there is written over.

${table('rom', 'num', bytes, 48)}

${table('dtb', 'num', dtb, 48)}
`;
}

// ---------------------------------------------------------------------------
// The stage
// ---------------------------------------------------------------------------

/// The stage the project is built for, and the grid that fits it.
///
/// Not measured at run time: a stage is what the project is *put* in, so it is a
/// build argument. Scratch's own is 480 by 360; TurboWarp's can be anything, and
/// the project built for one has to be run in a stage of that size, which is why
/// the size is written into the project rather than looked for by it.
///
/// The grid is whole 7 by 16 cells inside the box the pen may be moved in, which
/// is the stage less `PEN_MARGIN` at every edge -- the box `lib/penfont` clips
/// at, so a cell laid out past it would be drawn and its ink would not.
function stage(width, height) {
    const PEN_MARGIN = 15;
    const CELL_W = 7, CELL_H = 16;
    const cols = Math.floor((width - PEN_MARGIN * 2) / CELL_W);
    const rows = Math.floor((height - PEN_MARGIN * 2) / CELL_H);
    const source = `// The stage this project was built for, written by tools/build.mjs. Do not
// edit: \`--stage WxH\` decides it, and without one it is the 480 by 360 that
// Scratch itself has. A TurboWarp stage is resized by hand to this size.
//
// The grid is whole 7 by 16 cells inside the box the pen may be moved in, which
// is the stage less ${PEN_MARGIN} units at every edge: that is where \`lib/penfont\`
// clips, so a cell past it is drawn and its ink is not.

pub const SCREEN_W: num = ${width};
pub const SCREEN_H: num = ${height};
pub const SCREEN_COLS: num = ${cols};
pub const SCREEN_ROWS: num = ${rows};
pub const SCREEN_LEFT: num = ${-cols * CELL_W / 2};
pub const SCREEN_TOP: num = ${rows * CELL_H / 2};
`;
    return { source, cols, rows };
}

// ---------------------------------------------------------------------------
// The run
// ---------------------------------------------------------------------------

const argv = process.argv.slice(2);
const stageArg = argv.indexOf('--stage');
if (stageArg >= 0 && !/^\d+x\d+$/i.test(argv[stageArg + 1] ?? '')) {
    console.error('usage: --stage WxH, the stage this project is built for -- e.g. --stage 1280x900');
    process.exit(2);
}
const [stageW, stageH] = stageArg >= 0
    ? argv[stageArg + 1].toLowerCase().split('x').map(Number)
    : [480, 360];

const screen = stage(stageW, stageH);
write('src/screen.rav', screen.source);
console.log(`examples/raven/rv32ima/src/screen.rav  ${stageW}x${stageH} stage, ` +
    `${screen.cols}x${screen.rows} cells`);

const generated = write('src/rv32/tables.rav', tables());
console.log(`${path.relative(process.cwd(), generated.file)}  ${(generated.size / 1048576).toFixed(1)} MB`);

const manifest = path.join(root, IMAGE.manifest);
const named = /name\s*=\s*"([^"]+)"/.exec(fs.readFileSync(manifest, 'utf8'));
const bytes = [...fs.readFileSync(path.join(root, IMAGE.file))];
const tree = [...fs.readFileSync(path.join(root, IMAGE.dtb))];
const written = write('src/rv32/image.rav', image(IMAGE.name, bytes, tree, `this repository's ${IMAGE.file}`));
console.log(`${path.relative(process.cwd(), written.file)}  ${IMAGE.name}: ${bytes.length} bytes, ` +
    `${(written.size / 1048576).toFixed(1)} MB of source`);
execFileSync('cargo', ['run', '--release', '-q', '-p', 'raven', '--', 'build', '-m', manifest],
    { cwd: repo, stdio: 'inherit' });
console.log(`  dist/${named[1]}.sb3`);
