//! Generates the block reference shipped in the documentation and printed by
//! `raven-asm catalog`. The catalog is the single source of truth, so the docs can
//! never drift from the compiler.

use raven_scratch::catalog::{self, BlockKind, Category, MenuDomain, Shape, Stability, Wire};
use std::collections::BTreeSet;

/// Machine-readable catalog as JSON.
pub fn json() -> serde_json::Value {
    let blocks: Vec<serde_json::Value> = catalog::BLOCKS
        .iter()
        .map(|b| {
            serde_json::json!({
                "opcode": b.opcode,
                "category": b.category.title(),
                "kind": kind_name(b.kind),
                "stability": match b.stability {
                    Stability::Vanilla => "vanilla",
                    Stability::Extended => "extended",
                },
                "extension": b.category.extension(),
                "text": b.text,
                "summary": b.summary,
                "body": match b.body {
                    raven_scratch::catalog::Body::None => "none",
                    raven_scratch::catalog::Body::Next => "next",
                    raven_scratch::catalog::Body::Substack => "substack",
                    raven_scratch::catalog::Body::SubstackElse => "substack+else",
                },
                "signature": signature(b),
                "args": b.args.iter().map(|a| serde_json::json!({
                    "name": a.name,
                    "wire": match a.wire { Wire::Input => "input", Wire::Field => "field" },
                    "shape": shape_name(a.shape),
                })).collect::<Vec<_>>(),
            })
        })
        .collect();
    serde_json::json!({ "blocks": blocks })
}

/// Plain text listing for the terminal.
pub fn text(filter: Option<&str>) -> String {
    let mut out = String::new();
    let mut current = None;
    for block in catalog::BLOCKS {
        if let Some(f) = filter {
            if !category_matches(block.category, f) {
                continue;
            }
        }
        if current != Some(block.category) {
            current = Some(block.category);
            out.push_str(&format!(
                "\n{}\n{}\n",
                block.category.title(),
                "-".repeat(block.category.title().len())
            ));
        }
        out.push_str(&format!("  {}\n", signature(block)));
        out.push_str(&format!("      {}\n", block.text));
    }
    if out.is_empty() {
        out.push_str("no blocks matched\n");
    }
    out
}

/// The Markdown block reference used by the VitePress site.
pub fn markdown() -> String {
    let mut out = String::new();

    out.push_str("<!-- Generated by `raven-asm catalog --markdown`. Do not edit by hand. -->\n\n");
    out.push_str("# Block reference\n\n");
    out.push_str(
        "Every raven-asm statement is exactly one Scratch block. The signature column \
         shows the arguments in the order they are written; `\"...\"` marks a dropdown \
         value, which is always a string literal.\n\n",
    );
    out.push_str(&format!(
        "The catalog currently contains **{} blocks**.\n\n",
        catalog::BLOCKS.len()
    ));

    let mut seen: Vec<Category> = Vec::new();
    for block in catalog::BLOCKS {
        if !seen.contains(&block.category) {
            seen.push(block.category);
        }
    }

    out.push_str("| Category | Blocks |\n| --- | --- |\n");
    for category in &seen {
        let count = catalog::BLOCKS
            .iter()
            .filter(|b| b.category == *category)
            .count();
        out.push_str(&format!(
            "| [{}](#{}) | {} |\n",
            category.title(),
            anchor(category.title()),
            count
        ));
    }
    out.push('\n');

    for category in seen {
        out.push_str(&format!("## {}\n\n", category.title()));
        let count = catalog::BLOCKS
            .iter()
            .filter(|b| b.category == category)
            .count();
        out.push_str(&format!("*{count} blocks.*\n\n"));

        for block in catalog::BLOCKS.iter().filter(|b| b.category == category) {
            out.push_str(&format!("### `{}`\n\n", block.opcode));
            out.push_str(&format!("{}\n\n", block.summary));

            let mut meta: Vec<String> = Vec::new();
            meta.push(format!("**Shape:** {}", kind_name(block.kind)));
            if block.stability == Stability::Extended {
                meta.push("**Runs on:** extended runtimes (TurboWarp), not vanilla Scratch".into());
            }
            if let Some(ext) = block.category.extension() {
                meta.push(format!("**Needs extension:** `{ext}`"));
            }
            match block.body {
                raven_scratch::catalog::Body::None => {}
                raven_scratch::catalog::Body::Next => {
                    meta.push("**Body:** `{ ... }` runs after the block".into())
                }
                raven_scratch::catalog::Body::Substack => {
                    meta.push("**Body:** `{ ... }` becomes the substack".into())
                }
                raven_scratch::catalog::Body::SubstackElse => {
                    meta.push("**Body:** `{ ... }` and `else { ... }`".into())
                }
            }
            out.push_str(&meta.join("  \n"));
            out.push_str("\n\n");

            // Source beside Scratch, the same two-column comparison the themed pages
            // use. Every blank line here is load-bearing: VitePress ends the raw
            // `<div>` block at the first blank line so the fence and inline code are
            // parsed as Markdown.
            out.push_str("<div class=\"cmp\">\n");
            out.push_str("<div class=\"cmp-col\">\n<h4>raven-asm</h4>\n\n");
            out.push_str(&format!("```rasm\n{}\n```\n\n", signature(block)));
            out.push_str("</div>\n");
            out.push_str("<div class=\"cmp-col\">\n<h4>Scratch</h4>\n\n");
            match scratch_blocks(block) {
                // The docs theme draws `<code class="b">` with scratchblocks, so the
                // reader sees the block itself rather than its text.
                Some(code) => out.push_str(&format!("<code class=\"b\" v-pre>{code}</code>\n\n")),
                None => out.push_str(&format!("`{}`\n\n", block.text)),
            }
            out.push_str("</div>\n");
            out.push_str("</div>\n\n");

            if !block.args.is_empty() {
                out.push_str("| # | argument | Scratch name | kind | type |\n| --- | --- | --- | --- | --- |\n");
                for (i, arg) in block.args.iter().enumerate() {
                    out.push_str(&format!(
                        "| {} | `{}` | `{}` | {} | {} |\n",
                        i + 1,
                        arg.name.to_ascii_lowercase(),
                        arg.name,
                        match arg.wire {
                            Wire::Input => "input",
                            Wire::Field => "field",
                        },
                        shape_name(arg.shape),
                    ));
                }
                out.push('\n');
            }
        }
    }

    out.push_str("## Dropdown values\n\n");
    out.push_str(
        "Dropdowns are checked while compiling. Values are matched case-insensitively \
         and written in the canonical spelling listed here.\n\n",
    );
    let mut printed: BTreeSet<&str> = BTreeSet::new();
    for block in catalog::BLOCKS {
        for arg in block.args {
            let Shape::Menu(id) = arg.shape else { continue };
            if !printed.insert(id) {
                continue;
            }
            if let Some(values) = catalog::fixed_menu_values(id) {
                out.push_str(&format!("- `{id}`: {}\n", code_list(values)));
                continue;
            }
            if let Some(spec) = catalog::MENUS.iter().find(|m| m.id == id) {
                match spec.domain {
                    MenuDomain::Fixed(values) => {
                        out.push_str(&format!("- `{id}`: {}\n", code_list(values)))
                    }
                    MenuDomain::Costumes => {
                        out.push_str(&menu_line(id, "the costumes declared by this target"))
                    }
                    MenuDomain::Backdrops => {
                        out.push_str(&menu_line(id, "the backdrops declared by the stage"))
                    }
                    MenuDomain::Sounds => {
                        out.push_str(&menu_line(id, "the sounds declared by this target"))
                    }
                    MenuDomain::Sprites(extras) => {
                        let names = code_list(extras);
                        out.push_str(&menu_line(id, &format!("every sprite name, plus {names}")));
                    }
                    MenuDomain::Open => out.push_str(&menu_line(id, "any value the block accepts")),
                }
            } else {
                out.push_str(&menu_line(
                    id,
                    "free-form; see the block's Scratch definition",
                ));
            }
        }
    }

    out
}

fn code_list(values: &[&str]) -> String {
    values
        .iter()
        .map(|v| format!("`{v}`"))
        .collect::<Vec<_>>()
        .join(", ")
}

/// Blocks that keep their plain Scratch text instead of a picture.
///
/// scratchblocks matches a block by its *text*, so two blocks that share one
/// label are indistinguishable to it, and the blocks Scratch 2 had but Scratch 3
/// dropped have no picture at all. Drawing those would show the wrong colour or a
/// greyed-out block, which is worse than showing the text.
const NOT_DRAWABLE: &[&str] = &[
    "argument_reporter_boolean",
    "argument_reporter_string_number",
    "control_all_at_once",
    "control_clear_counter",
    "control_for_each",
    "control_get_counter",
    "control_if_else",
    "control_incr_counter",
    "control_while",
    "data_lengthoflist",
    "data_listcontainsitem",
    "data_listcontents",
    "data_variable",
    "operator_mathop",
    "sound_changeeffectby",
    "sound_seteffectto",
];

/// The block as scratchblocks source, or `None` when it cannot be drawn.
///
/// Every `%n` placeholder in the catalog's Scratch text becomes an empty input of
/// the matching shape — `()` for a round slot, `<>` for a boolean and `[]` for a
/// dropdown — which is what makes the text parse back into the block it names.
fn scratch_blocks(block: &catalog::BlockSpec) -> Option<String> {
    if NOT_DRAWABLE.contains(&block.opcode) {
        return None;
    }

    let mut out = String::new();
    let mut rest = block.text;
    while let Some(at) = rest.find('%') {
        push_literal(&mut out, &rest[..at]);
        let digits: String = rest[at + 1..]
            .chars()
            .take_while(|c| c.is_ascii_digit())
            .collect();
        match digits.parse::<usize>() {
            Ok(n) if n > 0 => {
                out.push_str(match block.args.get(n - 1).map(|arg| arg.shape) {
                    Some(Shape::Bool) => "&lt;&gt;",
                    Some(Shape::Menu(_)) => "[]",
                    _ => "()",
                });
                rest = &rest[at + 1 + digits.len()..];
            }
            _ => {
                out.push('%');
                rest = &rest[at + 1..];
            }
        }
    }
    push_literal(&mut out, rest);
    Some(out)
}

/// Copy literal block text, escaping what HTML or scratchblocks would read as
/// markup. `<` needs both: `&lt;` for HTML, and a backslash for scratchblocks,
/// which would otherwise take it for the start of a boolean input. The backslash
/// is the numeric entity `&#92;` because the site's Markdown renderer treats the
/// text between two raw HTML tags as Markdown, and a plain `\&lt;` would come out
/// of that as a literal `&lt;`.
fn push_literal(out: &mut String, text: &str) {
    for ch in text.chars() {
        match ch {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&#92;&lt;"),
            '>' => out.push_str("&gt;"),
            _ => out.push(ch),
        }
    }
}

/// One dropdown bullet: the menu id, then its domain.
fn menu_line(id: &str, text: &str) -> String {
    format!("- `{id}`: {text}\n")
}

pub fn signature(block: &catalog::BlockSpec) -> String {
    let args: Vec<String> = block
        .args
        .iter()
        .map(|a| match a.shape {
            Shape::Menu(_) => format!("\"{}\"", a.name.to_ascii_lowercase()),
            _ => a.name.to_ascii_lowercase(),
        })
        .collect();
    // Reporters always need their parentheses; command blocks may drop them.
    let needs_parens = !args.is_empty() || block.kind.is_value();
    let mut sig = if needs_parens {
        format!("{}({});", block.opcode, args.join(", "))
    } else {
        format!("{};", block.opcode)
    };
    match block.body {
        raven_scratch::catalog::Body::None => {}
        raven_scratch::catalog::Body::Next | raven_scratch::catalog::Body::Substack => {
            sig = sig.replace(';', " { ... }");
        }
        raven_scratch::catalog::Body::SubstackElse => {
            sig = sig.replace(';', " { ... } else { ... }");
        }
    }
    sig
}

fn kind_name(kind: BlockKind) -> &'static str {
    match kind {
        BlockKind::Hat => "hat",
        BlockKind::Stack => "stack",
        BlockKind::Cap => "cap",
        BlockKind::Reporter => "reporter",
        BlockKind::Boolean => "boolean",
    }
}

fn shape_name(shape: Shape) -> String {
    match shape {
        Shape::Number => "number".into(),
        Shape::Positive => "positive number".into(),
        Shape::Whole => "whole number".into(),
        Shape::Integer => "integer".into(),
        Shape::Angle => "angle".into(),
        Shape::Text => "text".into(),
        Shape::Color => "colour `\"#rrggbb\"`".into(),
        Shape::Variable => "variable name".into(),
        Shape::List => "list name".into(),
        Shape::Broadcast => "broadcast message".into(),
        Shape::Bool => "boolean".into(),
        Shape::Menu(id) => format!("dropdown `{id}`"),
        Shape::ParamName => "parameter name".into(),
    }
}

fn category_matches(category: Category, filter: &str) -> bool {
    let f = filter.to_ascii_lowercase();
    category.title().to_ascii_lowercase().contains(&f)
        || category.extension().is_some_and(|e| e == f)
}

fn anchor(title: &str) -> String {
    title
        .to_ascii_lowercase()
        .chars()
        .map(|c| if c.is_ascii_alphanumeric() { c } else { '-' })
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn markdown_mentions_every_block() {
        let md = markdown();
        for block in catalog::BLOCKS {
            assert!(
                md.contains(&format!("### `{}`", block.opcode)),
                "missing {} from the generated reference",
                block.opcode
            );
        }
    }

    #[test]
    fn json_lists_every_block() {
        let value = json();
        let blocks = value["blocks"].as_array().expect("array");
        assert_eq!(blocks.len(), catalog::BLOCKS.len());
    }

    #[test]
    fn the_scratch_rendering_is_either_a_picture_or_the_plain_text() {
        let md = markdown();
        let mut pictures = 0;
        for line in md
            .lines()
            .filter(|l| l.starts_with("<code class=\"b\" v-pre>"))
        {
            pictures += 1;
            assert!(
                !line
                    .char_indices()
                    .any(|(i, c)| c == '%'
                        && line[i + 1..].starts_with(|d: char| d.is_ascii_digit())),
                "a drawn block still has a placeholder: {line}"
            );
            assert!(
                line.ends_with("</code>"),
                "a drawn block is not closed: {line}"
            );
        }
        let drawable = catalog::BLOCKS
            .iter()
            .filter(|b| scratch_blocks(b).is_some())
            .count();
        assert_eq!(
            pictures, drawable,
            "every drawable block needs its Scratch picture"
        );

        for block in catalog::BLOCKS
            .iter()
            .filter(|b| scratch_blocks(b).is_none())
        {
            assert!(
                md.contains(&format!("`{}`\n", block.text)),
                "{} is not rendered as plain text",
                block.opcode
            );
        }
    }

    #[test]
    fn the_not_drawable_list_only_names_real_blocks() {
        for opcode in NOT_DRAWABLE {
            assert!(
                catalog::BLOCKS.iter().any(|b| b.opcode == *opcode),
                "{opcode} is on the list but is not a block"
            );
        }
    }

    #[test]
    fn a_boolean_placeholder_becomes_an_empty_boolean_input() {
        let and = catalog::BLOCKS
            .iter()
            .find(|b| b.opcode == "operator_and")
            .expect("operator_and");
        assert_eq!(
            scratch_blocks(and).as_deref(),
            Some("&lt;&gt; and &lt;&gt;")
        );

        let lt = catalog::BLOCKS
            .iter()
            .find(|b| b.opcode == "operator_lt")
            .expect("operator_lt");
        assert_eq!(scratch_blocks(lt).as_deref(), Some("() &#92;&lt; ()"));
    }
}
