//! The human documentation, embedded verbatim.
//!
//! The reference pages above this group are written for a generator: dense, and
//! generated from the compiler's tables wherever a table exists. These are the
//! prose pages from `docs/`, included so that nothing about raven requires the
//! repository or a website — the long version of any terse reference page is
//! here, and a page with no reference counterpart (a tutorial, a rationale, a
//! list of rejected designs) is here and nowhere else.
//!
//! `include_str!` is relative to this file, so `../..` walks back to the
//! repository root. The generated block reference is included too: it is
//! regenerated by `raven-asm catalog --markdown`, which is the same text.

/// One embedded documentation page: a heading, one line saying what this is,
/// then the file exactly as it is on disk.
macro_rules! guide {
    ($id:literal, $shown:literal) => {
        concat!(
            "\n## ",
            $id,
            "\n# The human documentation, verbatim: ",
            $shown,
            "\n# Written for a person. Where the material above has a reference page too, the\n\
             # index lists both; where it does not, this is the only place it is written down.\n\n",
            include_str!(concat!("../../../../", $shown))
        )
    };
}

pub const INDEX: &str = guide!("docs/index", "docs/index.md");

pub const GUIDE_INDEX: &str = guide!("docs/guide/index", "docs/guide/index.md");
pub const GETTING_STARTED: &str = guide!(
    "docs/guide/getting-started",
    "docs/guide/getting-started.md"
);
pub const FOR_LLMS: &str = guide!("docs/guide/for-llms", "docs/guide/for-llms.md");

pub const RAVEN_INDEX: &str = guide!("docs/raven/index", "docs/raven/index.md");
pub const RAVEN_DESIGN: &str = guide!("docs/raven/design", "docs/raven/design.md");
pub const RAVEN_SYNTAX: &str = guide!("docs/raven/syntax", "docs/raven/syntax.md");
pub const RAVEN_TYPES: &str = guide!("docs/raven/types", "docs/raven/types.md");
pub const RAVEN_STD: &str = guide!("docs/raven/std", "docs/raven/std.md");
pub const RAVEN_MACROS: &str = guide!("docs/raven/macros", "docs/raven/macros.md");
pub const RAVEN_MODULES: &str = guide!("docs/raven/modules", "docs/raven/modules.md");
pub const RAVEN_LOWERING: &str = guide!("docs/raven/lowering", "docs/raven/lowering.md");
pub const RAVEN_CLI: &str = guide!("docs/raven/cli", "docs/raven/cli.md");
pub const RAVEN_FROM_SCRUST: &str = guide!("docs/raven/from-scrust", "docs/raven/from-scrust.md");

pub const ASM_INDEX: &str = guide!("docs/raven-asm/index", "docs/raven-asm/index.md");
pub const ASM_DESIGN: &str = guide!("docs/raven-asm/design", "docs/raven-asm/design.md");
pub const ASM_SYNTAX: &str = guide!("docs/raven-asm/syntax", "docs/raven-asm/syntax.md");
pub const ASM_BLOCKS: &str = guide!("docs/raven-asm/blocks", "docs/raven-asm/blocks.md");
pub const ASM_VARIABLES: &str = guide!("docs/raven-asm/variables", "docs/raven-asm/variables.md");
pub const ASM_PROCEDURES: &str =
    guide!("docs/raven-asm/procedures", "docs/raven-asm/procedures.md");
pub const ASM_ASSETS: &str = guide!("docs/raven-asm/assets", "docs/raven-asm/assets.md");
pub const ASM_PROJECT_STRUCTURE: &str = guide!(
    "docs/raven-asm/project-structure",
    "docs/raven-asm/project-structure.md"
);
pub const ASM_MULTI_FILE: &str =
    guide!("docs/raven-asm/multi-file", "docs/raven-asm/multi-file.md");
pub const ASM_CLI: &str = guide!("docs/raven-asm/cli", "docs/raven-asm/cli.md");
pub const ASM_TROUBLESHOOTING: &str = guide!(
    "docs/raven-asm/troubleshooting",
    "docs/raven-asm/troubleshooting.md"
);
pub const ASM_OPTIMIZER: &str = guide!("docs/raven-asm/optimizer", "docs/raven-asm/optimizer.md");

pub const RE_INDEX: &str = guide!("docs/raven-re/index", "docs/raven-re/index.md");
pub const RE_CLI: &str = guide!("docs/raven-re/cli", "docs/raven-re/cli.md");

pub const REFERENCE_BLOCKS: &str = guide!("docs/reference/blocks", "docs/reference/blocks.md");
